version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:12.13

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: yarn install
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./*
  test:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

   release:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run: yarn release

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build                  
      - release:
          requires:
            - test
          filters:
            branches:
              only: master